def haystack(dna, sub):
    position = []
    length=len(sub)
    for i in range(len(dna)):
        if dna[i: i + length ] == sub:
            position.append(i+1)

    print(*position) #print as space separated elements


dna = 'TCCAGTTAGCCTATAGCCCTATAGCCCCTATAGAGGAAGGACCTATAGAATTCTCCGATCCTATAGGTGGCCTATAGGAACCTTCCTATAGCTTGATGCGCCTATAGACCTATAGCCTATAGGCGGGCCTATAGGGGGTCCCTATCCTATAGGTTTATAACCTATAGACCCTATAGCCTATAGCCTATAGCCCTATAGCCCTATAGCCTATAGACCTATAGGCCTCCTATAGCCTATAGTCCTATAGTCGCCTATAGGCCTATAGAATGCGCGCCTAGCCTATAGTCCTATAGGGCCTATAGCCTATAGTCGCGCCTATAGCTTCCTATAGTCCTATAGACCCTATAGGTTTCGGCCTATAGACCTATAGGTCTCCTATAGGTACCTATAGCCTATAGGGTGTACCTATAGGCCCTATAGCCTATAGATAAATAACCCTATAGACCTATAGCCTATAGCCTATAGCCTATAGAAAGCCTATAGGGCTCCTATAGCCTATAGTTCCTATAGCCTATAGGCCTATAGTCCCTATAGTCCCTATAGCCTATAGTGGCCTATAGCCTATAGCCTATAGACCTATAGCCTATAGTTTGCCTATAGATTACCTATCCTATAGCACCTATAGCCTATAGGACCTATAGCCCCTATAGAGACACAACGCGTCCGGTGGCTGCTACCTATAGCCTATAGGCCTATAGGCCTATAGCCCTATAGAGCCCTATAGTGCCCCTATAGATCCTATAGTTACCTATAGCCTATAGCGTCCTATAGAGACGCCTATAGCTGAGCGCCTATAGGACACATAAAACGGC'
sub = 'CCTATAGCC'

haystack(dna, sub)






